name: LazyPagination
author: rpflorence@gmail.com
category: Interface
tags: [request, navigation]
docs: http://moodocs.net/rpflo/mootools-rpflo/LazyPagination
demo: http://ryanflorence.com/scripts/mootools/LazyPagination/Demos/
current: 1.2